name: Releases

env:
  PLUGIN_NAME: better-workflow
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Get next version
        run: npx semantic-release --dry-run --no-ci

      - name: Build dist
        run: pnpm build

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Create ZIP file
        run: zip -r release.zip . -x "node_modules/*" ".git/*"

      - name: Release
        run: npx semantic-release 
